name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']
    # types: [opened, reopened, synchronize, ready_for_review] # Vous pouvez affiner les types si besoin
  # Permet le déclenchement manuel du job 'deploy' depuis l'interface GitHub Actions
  workflow_dispatch:

jobs:
  # ==========================================
  # Job: Test
  # ==========================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    # Variables d'environnement pour les tests
    env:
      NODE_ENV: test
      PORT: 8000
      DB_TYPE: mysql
      DB_HOST: localhost
      DB_PORT: 3307
      DB_USERNAME: test_user
      DB_PASSWORD: test_pwd
      DB_NAME: test_db
      JWT_SECRET: test_jwt_secret_key_for_ci_pipeline_only
      REDIS_URL: redis://localhost:6380
      GOOGLE_CLIENT_ID: test_google_client_id
      GOOGLE_CLIENT_SECRET: test_google_client_secret
      GOOGLE_CALLBACK_URL: http://localhost:8000/api/v1/auth/google/callback
      MAIL_HOST: localhost
      MAIL_PORT: 1025
      MAIL_USER: test@example.com
      MAIL_PASS: test_password
      MAIL_FROM: noreply@example.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Optionnel: Linting/Formatting
      - name: Lint code
        run: npm run lint
      - name: Check formatting
        run: npm run format

      - name: Ensure test services are stopped
        # Arrête et supprime les conteneurs/volumes précédents via le script npm
        run: npm run test-db:stop
        # Continue même si la commande échoue (par exemple, si les conteneurs n'existaient pas)
        continue-on-error: true

      - name: Start test services
        # Utilise --wait pour attendre que les conteneurs avec healthcheck soient sains (mysql-test, redis-test)
        run: docker compose -f src/tests/docker-compose.yml up -d --wait

      - name: Wait for services to stabilize
        run: sleep 10s

      - name: Verify database connection
        run: |
          echo "Testing MySQL connection..."
          docker exec mysql-test mysql -u test_user -ptest_pwd -e "SELECT 1;" test_db
          echo "MySQL is ready!"

      - name: Verify Redis connection
        run: |
          echo "Testing Redis connection..."
          docker exec redis-test redis-cli ping
          echo "Redis is ready!"

      - name: Initialize database with test data
        run: |
          echo "Initializing database with test data..."
          docker exec mysql-test mysql -u test_user -ptest_pwd test_db < src/tests/db-data/0-grant-permission.sql
          docker exec mysql-test mysql -u test_user -ptest_pwd test_db < src/tests/db-data/1-schema.sql
          docker exec mysql-test mysql -u test_user -ptest_pwd test_db < src/tests/db-data/2-datas.sql
          echo "Database initialized!"

      - name: Run tests
        # Utilise le script test:ci qui n'utilise pas dotenv-cli
        run: npm run test:ci

      - name: Stop test services
        if: always()
        run: docker compose -f src/tests/docker-compose.yml down -v

  # ==========================================
  # Job: Build and Push Docker Image
  # ==========================================
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # Ne s'exécute que sur push vers 'main' et après succès du job 'test'
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
    needs: test

    # Accorde les permissions nécessaires pour lire le contenu et écrire des packages (images Docker)
    permissions:
      contents: read # Nécessaire pour actions/checkout
      packages: write # Nécessaire pour pusher vers GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Utilise le token fourni automatiquement par GitHub Actions
          username: ${{ github.actor }} # L'utilisateur qui a déclenché le workflow
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Construit le nom de l'image pour GHCR: ghcr.io/owner/repo
          # Vous pouvez ajouter un nom d'image spécifique si besoin: ghcr.io/${{ github.repository }}/api
          images: ghcr.io/${{ github.repository }} # Ex: ghcr.io/adamsbarry18/api.template.node
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ===========================================
  # Job: Deploy (Manual Trigger)
  # ===========================================